#%RAML 1.0
---
title: ANGELSAFE API
version: v0.1.0

/api/auth/register:
    post:
        body:
            application/json:
                example: |
                    {
                        "mobileNumber": 09123456789
                    }
        responses:
            200:
                body:
                    application/json:
                        example: |
                            {
                                "mobileNumber": 09123456789
                            }
/api/auth/register-email:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "email": "test@email.com",
                        "password": "thisIsMyPassword"
                    }
        responses:
            200:
                body:
                    application/json:
                        example: |
                            {
                                "email": "test@email.com",
                            }
/api/auth/otp:
    post:
        body:
            application/json:
                example: |
                    {
                        "mobileNumber": 09123456789
                    }
        responses:
            200:
                body:
                    application/json:
                        example: |
                            {
                                "mobileNumber": 09123456789
                            }
/api/auth/login:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Basic authentication base 64 encoded string
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "mfa": "1"
                    }
        responses:
            200:
                body:
                    application/json:
                        example: |
                            {
                                "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c",
                            }
/api/profile/register:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "username": "testeruser",
                        "year": "1994",
                        "country": "Philippines",
                        "gender": "Male"
                    }
        responses:
            200:
                body:
                    application/json:
                        example: null
/api/profile/update:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "country": "Canada",
                        "gender": "Female"
                    }
        responses:
            200:
                body:
                    application/json:
                        example: null
/api/profile/info:
    get:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        responses:
            200:
                body:
                    application/json:
                        example: |
                            {
                                "username": "johnytest",
                                "profilePic": "data:image/png;base64,iVY...",
                                "year": "1994",
                                "gender": "Female",
                                "country": "North Korea"
                            }
/api/profile/update-pic:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "profilePic": "data:image/png;base64,iVY..."
                    }
        responses:
            200:
                body:
                    application/json:
                        example: null
/api/group/register:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "groupname": "angelsafe",
                        "description": "sample group for angelsafe"
                    }
        responses:
            200:
                body:
                    application/json:
                        example: null
/api/group/update:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "groupname": "angelsafev2",
                        "description": "sample group"
                    }
        responses:
            200:
                body:
                    application/json:
                        example: null
/api/group/update-pic:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "profilePic": "data:image/png;base64,iVY..."
                    }
        responses:
            200:
                body:
                    application/json:
                        example: null
/api/group/info:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "groupId": "Y3ODkwIiwibmFtZSI6Ikpva..."
                    }
        responses:
            200:
                body:
                    application/json:
                        example: |
                        {
                            "id": "Y3ODkwIiwibmFtZSI6Ikpva...",
                            "groupname": "angelsafev2",
                            "description": "sample group",
                            "profilePic": "data:image/png;base64,iVY..."
                        }
/api/group/join:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "groupId": "Y3ODkwIiwibmFtZSI6Ikpva...",
                    }
        responses:
            200:
                body:
                    application/json:
                        example: null
/api/group/unjoin:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "groupId": "Y3ODkwIiwibmFtZSI6Ikpva...",
                    }
        responses:
            200:
                body:
                    application/json:
                        example: null
/api/group/members:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "groupId": "Y3ODkwIiwibmFtZSI6Ikpva...",
                    }
        responses:
            200:
                body:
                    application/json:
                        example: |
                            {
                                <profiles>
                            }
/api/group/list:
    get:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        responses:
            200:
                body:
                    application/json:
                        example: |
                            {
                                <groups>
                            }
/api/group/ban:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "groupId": "Y3ODkwIiwibmFtZSI6Ikpva...",
                        "id": "kpvaG4gRG9lIiwiaWF0IjoxNTE..."
                    }
        responses:
            200:
                body:
                    application/json:
                        example: null
/api/chat/create:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "receiverId": "K3OasvdgiwibmFtZSI6Ikpva...",
                        "message": "This is a test message..."
                    }
        responses:
            200:
                body:
                    application/json:
                        example: null
/api/chat/view:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "receiverId": "K3OasvdgiwibmFtZSI6Ikpva...",
                    }
        responses:
            200:
                body:
                    application/json:
                        example: |
                            [{
                                "id": "635429a9756d27bdb4...",
                                "timestamp": 1666460073913,
                                "message": "Test Message 2",
                                "sender": <profile>,
                                "receiver": <profile>
                            }]
/api/chat/list:
    get:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        responses:
            200:
                body:
                    application/json:
                        example: |
                            {
                                "id": "6354e7cda1076d0dfc...",
                                "receiver": <profile>,
                                "read": 1,
                                "lastMessage": "Test Message 1..."
                            }
/api/stat/create:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "stat": "2"
                    }
        responses:
            200:
                body:
                    application/json:
                        example: null
/api/stat/view:
    get:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        responses:
            200:
                body:
                    application/json:
                        example: |
                            {
                                "id": "635429a9756d27bdb4...",
                                "stat": 2,
                            }
/api/post/create:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "message": "This is a sample Post"
                    }
        responses:
            200:
                body:
                    application/json:
                        example: null
/api/post/view:
    get:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        responses:
            200:
                body:
                    application/json:
                        example: |
                            {
                                "id": "635429a9756d27bdb4...",
                                "message": "This is a sample Post",
                                "timestamp" 12355476565,
                                "comments": 12,
                                "hearts": 3,
                                "likes": 56
                            }
/api/post/heart:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "postId": "635429a9756d27bdb4..."
                    }
        responses:
            200:
                body:
                    application/json:
                        example: null
/api/post/like:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "postId": "635429a9756d27bdb4..."
                    }
        responses:
            200:
                body:
                    application/json:
                        example: null
/api/post/unheart:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "postId": "635429a9756d27bdb4..."
                    }
        responses:
            200:
                body:
                    application/json:
                        example: null
/api/post/unlike:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "postId": "635429a9756d27bdb4..."
                    }
        responses:
            200:
                body:
                    application/json:
                        example: null