#%RAML 1.0
---
title: ANGELSAFE API
version: v0.1.0

/api/auth/register:
    post:
        body:
            application/json:
                example: |
                    {
                        "mobileNumber": 09123456789
                    }
        responses:
            200:
                body:
                    application/json:
                        example: |
                            {
                                "mobileNumber": 09123456789
                            }
/api/auth/register-email:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "email": "test@email.com",
                        "password": "thisIsMyPassword"
                    }
        responses:
            200:
                body:
                    application/json:
                        example: |
                            {
                                "email": "test@email.com",
                            }
/api/auth/otp:
    post:
        body:
            application/json:
                example: |
                    {
                        "mobileNumber": 09123456789
                    }
        responses:
            200:
                body:
                    application/json:
                        example: |
                            {
                                "mobileNumber": 09123456789
                            }
/api/auth/login:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Basic authentication base 64 encoded string
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "mfa": "1"
                    }
        responses:
            200:
                body:
                    application/json:
                        example: |
                            {
                                "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MD...",
                            }
/api/auth/refresh-token:
    get:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        responses:
            200:
                body:
                    application/json:
                        example: |
                            {
                                "token": "eyJhbtYroiEkdATI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MD..."
                            }
/api/profile/register:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "username": "testeruser",
                        "year": "1994",
                        "country": "Philippines",
                        "gender": "Male"
                    }
        responses:
            200:
                body:
                    application/json:
                        example: null
/api/profile/update:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "username":"testuser",
                        "year": "1994",
                        "country": "United States of America",
                        "gender": "Male",
                        "bio": "This is my personal bio",
                        "hobbies": ["Cooking"],
                        "music": ["Gothic Metal"],
                        "movies": ["American Pie"]
                    }
        responses:
            200:
                body:
                    application/json:
                        example: null
/api/profile/info:
    get:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        responses:
            200:
                body:
                    application/json:
                        example: |
                            {
                                "id": "Y3ODkwIiwibmFtZSI6Ikpva...",
                                "username":"testuser",
                                "year": "1994",
                                "country": "United States of America",
                                "gender": "Male",
                                "bio": "This is my personal bio",
                                "hobbies": ["Cooking"],
                                "music": ["Gothic Metal"],
                                "movies": ["American Pie"],
                                "mobileNumber": "+639452224444",
                                "email": "test@email.com",
                                "winCount": 1,
                                "painCount": 0
                            }
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "ids": ["635400ee05aa48461a..."]
                    }
        responses:
            200:
                body:
                    application/json:
                        example: |
                            [{
                                "id": "Y3ODkwIiwibmFtZSI6Ikpva...",
                                "username":"testuser",
                                "year": "1994",
                                "country": "United States of America",
                                "gender": "Male",
                                "bio": "This is my personal bio",
                                "hobbies": ["Cooking"],
                                "music": ["Gothic Metal"],
                                "movies": ["American Pie"]
                            }]
/api/profile/update-pic:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "profilePic": "data:image/png;base64,iVY..."
                    }
        responses:
            200:
                body:
                    application/json:
                        example: null
/api/group/register:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "groupname": "angelsafe",
                        "description": "sample group for angelsafe"
                    }
        responses:
            200:
                body:
                    application/json:
                        example: null
/api/group/update:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "groupname": "angelsafev2",
                        "description": "sample group"
                    }
        responses:
            200:
                body:
                    application/json:
                        example: null
/api/group/update-pic:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "profilePic": "data:image/png;base64,iVY..."
                    }
        responses:
            200:
                body:
                    application/json:
                        example: null
/api/group/info:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "groupId": "Y3ODkwIiwibmFtZSI6Ikpva..."
                    }
        responses:
            200:
                body:
                    application/json:
                        example: |
                        {
                            "id": "Y3ODkwIiwibmFtZSI6Ikpva...",
                            "groupname": "angelsafev2",
                            "description": "sample group",
                            "profilePic": "data:image/png;base64,iVY...",
                            "members": 3,
                            "joined": 1,
                            "online": 2
                        }
/api/group/join:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "groupId": "Y3ODkwIiwibmFtZSI6Ikpva...",
                    }
        responses:
            200:
                body:
                    application/json:
                        example: null
/api/group/unjoin:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "groupId": "Y3ODkwIiwibmFtZSI6Ikpva...",
                    }
        responses:
            200:
                body:
                    application/json:
                        example: null
/api/group/members:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "groupId": "Y3ODkwIiwibmFtZSI6Ikpva...",
                    }
        responses:
            200:
                body:
                    application/json:
                        example: |
                            {
                                <profiles>
                            }
/api/group/list:
    get:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        responses:
            200:
                body:
                    application/json:
                        example: |
                            {
                                <groups>
                            }
/api/group/ban:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "groupId": "Y3ODkwIiwibmFtZSI6Ikpva...",
                        "id": "kpvaG4gRG9lIiwiaWF0IjoxNTE..."
                    }
        responses:
            200:
                body:
                    application/json:
                        example: null
/api/notif/list:
    get:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        responses:
            200:
                body:
                    application/json:
                        example: |
                            [{
                                "timestamp": 1667177573287,
                                "message": "You have created the AngelSafe group.",
                                "read": 1,
                                "profilePic": "data:image/png;base64,iVBORw0KGgoAAAANSUh...",
                                "groupname": "AngelSafe",
                                "groupId": "635400ee05aa48461..."
                            }]
/api/chat/create:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "receiverId": "K3OasvdgiwibmFtZSI6Ikpva...",
                        "message": "This is a test message..."
                    }
        responses:
            200:
                body:
                    application/json:
                        example: null
/api/chat/view:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "receiverId": "K3OasvdgiwibmFtZSI6Ikpva...",
                    }
        responses:
            200:
                body:
                    application/json:
                        example: |
                            [{
                                "id": "635429a9756d27bdb4...",
                                "timestamp": 1666460073913,
                                "message": "Test Message 2",
                                "sender": <profile>,
                                "receiver": <profile>
                            }]
/api/chat/list:
    get:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        responses:
            200:
                body:
                    application/json:
                        example: |
                            {
                                "id": "6354e7cda1076d0dfc...",
                                "receiver": <profile>,
                                "635688a18c45f900...": 3, // # of unread messages
                                "635400ee05aa4846...": 0, //read
                                "lastMessage": "Test Message 1...",
                                "lastMessageTimestamp": 1666460073913
                            }
/api/stat/create:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "stat": "2",
                        "experience": ["Tired"]
                    }
        responses:
            200:
                body:
                    application/json:
                        example: null
/api/stat/chart:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "groupId": "6354e7cda1076d0dfc..."
                    }
        responses:
            200:
                body:
                    application/json:
                        example: |
                            {
                                "1": 30,
                                "2": 50,
                                "3": 10,
                                "4": 5,
                                "5": 5
                            }
/api/stat/view:
    get:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        responses:
            200:
                body:
                    application/json:
                        example: |
                            {
                                "id": "635429a9756d27bdb4...",
                                "stat": 2,
                                "experience": ["Tired"]
                            }
/api/post/create:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "message": "This is a sample Post",
                        "groupId": "635429a9756d27bdb4...",
                    }
        responses:
            200:
                body:
                    application/json:
                        example: null
/api/post/view:
    get:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        responses:
            200:
                body:
                    application/json:
                        example: |
                            [{
                                "id": "635429a9756d27bdb4...",
                                "ownerId": "635429a9756d346fs3...",
                                "groupId": "635429a97234tdsg45...",
                                "message": "This is a sample Post",
                                "timestamp" 12355476565,
                                "comments": 12,
                                "hearts": 3,
                                "likes": 56
                            }]
/api/post/list:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "groupId": "635429a97234tdsg45...",
                        "skip": 0
                    }
        responses:
            200:
                body:
                    application/json:
                        example: |
                            [{
                                "id": "635429a9756d27bdb4...",
                                "ownerId": "635429a9756d346fs3...",
                                "groupId": "635429a97234tdsg45...",
                                "message": "This is a sample Post",
                                "timestamp" 12355476565,
                                "comments": 12,
                                "hearts": 3,
                                "likes": 56
                            }]
/api/post/heart:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "postId": "635429a9756d27bdb4..."
                    }
        responses:
            200:
                body:
                    application/json:
                        example: null
/api/post/like:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "postId": "635429a9756d27bdb4..."
                    }
        responses:
            200:
                body:
                    application/json:
                        example: null
/api/post/unheart:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "postId": "635429a9756d27bdb4..."
                    }
        responses:
            200:
                body:
                    application/json:
                        example: null
/api/post/unlike:
    post:
        headers: 
            Authorization: 
                displayName: Authentication
                description: Bearer JWT
                type: string
                required: true
        body:
            application/json:
                example: |
                    {
                        "postId": "635429a9756d27bdb4..."
                    }
        responses:
            200:
                body:
                    application/json:
                        example: null