export const hobbies = [
  "Reading books",
  "Blogging",
  "Dancing",
  "Singing",
  "Listening to music",
  "Playing musical instruments",
  "Learning new languages",
  "Shopping",
  "Traveling",
  "Hiking",
  "Cycling",
  "Exercising",
  "Drawing",
  "Painting",
  "Collecting things",
  "Playing computer games",
  "Cooking",
  "Baking",
  "Gardening",
  "Handmade Crafts",
  "Embroidering",
  "Sewing",
  "Knitting",
  "Playing board games",
  "Walking",
  "Writing stories",
  "Fishing",
  "Photography",
  "Surfing",
  "Hiking",
  "Yoga",
];

export const movieGenres = [
  "Action",
  "Animation",
  "Comedy",
  "Crime",
  "Drama",
  "Experimental",
  "Fantasy",
  "Historical",
  "Horror",
  "Romance",
  "Science Fiction",
  "Thriller",
  "Western",
];

export const musicGenres = [
  "Rock",
  "Jazz",
  "Electronic Dance Music",
  "Dubstep",
  "Techno",
  "Rhythm and Blues (R&B)",
  "Country",
  "Pop",
  "Indie Rock",
  "Electro",
  "Metal",
];
